language: node_js
node_js:
- node
before_script:
- npm install -g npm@latest
- npm ci
script:
- npm test
- npm run build
deploy:
  on:
    tags: true
  skip_cleanup: true
  provider: npm
  email: elshinnaweyom@gmail.com
  api_key:
    secure: LJ1MT0nu97H3jFMN004tKhCQtqClEJoMMzVmOFMK25q3J4GNHKtDC0+twa4Uxn11COKs+sMGl1o3mNEDLQNxVNEbwuYcELVjjAfnIkFpNkCrkKXjOIpql2Cih+rml0kbZd/jDKvd8vK+nZPowHm7t4ygmTbID5FbRHgNafEdpTC+0TBorEi8D7vdNyyMy2iJSk/7ELIo4UBzLZ7KtoE20JcJhP1NOKAIp7W/mTfBiUTm8SzMQvDI9iiPMUz5V2myrlcUsHzYL092EgUTttM6j5kC7LzX5XrwcYMnDwssuPRGD/WVh1wF1mBQ2S7/Z12E+xNymY3Q2Eb26t1qekUitqqt2bwnXnZGRgRK+hO6BSo4q5k9erKpRDUU6frAyljjI2Un/CTv+9/sMnpJZuSknlIs+jtEAaU9g69pVHXRULYx0gCvkNxTbesGUmMj7UhEDC9ISTVQ498lhI1WeYlOJE//jl5YRMe1sAwHvYOmChVQfCRQCZEs8+3CM+nrxK5RPa9pmiJSoycwcD5O1LhrpU3rGgbLB6U71T+JSmihRk1LwxDvf9CF0qeGTmHsyxfNZyXqotvAh9zQHpYNh+KeNT7EMUvZK1H8l95WMIZ8Nt0QQqUGdQkujHyYDwMNKDtmhnLS/NJBs05c9exhS/J6UIUzgbbQ9dREnSo13HxjUf4=
