language: node_js
node_js:
- node
before_script:
- npm install -g npm@latest
- npm ci
script:
- npm test
- npm run build
deploy:
  on:
    tags: true
  skip_cleanup: true
  provider: npm
  email: elshinnaweyom@gmail.com
  api_key:
    secure: QSKz5FtZKPMcPRSPPqAncybzxbh9ApRPdGjbqMdCaF8mhP2mGbs9qQKTKW2lT4L9qN5xdIjgB9uX1xIbRXIPHLlIDY6unVTfD6vrY5NWt4vdpFo4Wi6hvKGFB0+ouPFy2+83IfleynMpsfQ2cAJ0UQ1Avb+xykt2ynwKmPI72KhGEXFdJblNHnhaqgkzcShQoAO9QAsbef7Uvwh06YtMq8C6ZfQOtOdmVAbhS+nRvqZoa7poEdEybB6sUxWLrL2OiV9uZS1CmaRE0mdhX0gwLBA6gCVjPixkRa0k1ddqDJjPsboO/hNpGzIE48UbTAdWLStUTjcCSv0bI9X6Hfu3xRsMyd/1k69vz0Js5R2a7VvHvkwK2WNxFQEZEEHvPrihN9z1Hxh9i+XOY+BCR5/WRAzb4syaTOQF8p3+sSsO/cI/AOdokxgDxHT485d730bHPM0srMwszXJ9ajxCpSZvp1Tr76PmvD3CVmzd8xOqQYf+B9EZxnDtDtOvPk6cRnA++8SM5O4D/g+OwCwGjgjZKYeweOQbNAE+ocpie58HE/BDtaRTR7ZwKJEQt8eWvdfWvS7y5XSOARbUB34gxOorON009wmi2FT9rGDp0I6a83Z8HSEZtFsy5Oz8Ox29Ya8/bPs9WqkUTR6yMBF6OCbzM7SkTAEOPEMICFZZMx76CaQ=
